#!/usr/bin/env python
"""Kotlin 포팅 검증용 픽스처 생성.

MediaPipe world landmark 로 만든 24관절 배열(cm, y 위+)과, 연구 코드(features.py)로 계산한
프레임 피처를 JSON 으로 덤프한다. Android 유닛 테스트(PostureCoreParityTest)가 같은 입력에
Kotlin 구현을 돌려 값이 일치하는지 비교한다.

출력: app/src/test/resources/posture_port_fixture.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from experiment_a import MP_MAP, build_mp_arrays, load_landmarks  # noqa: E402
from features import JOINTS_SHORT, compute_frame_features  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

OUT = HERE / "outputs"
DEST = HERE.parent.parent / "app" / "src" / "test" / "resources" / "posture_port_fixture.json"
N_FRAMES = 40
# 비교 제외:
#  spine_*, kneefoot_thigh, neck_angle — Back/Waist 가 필요해 MediaPipe 로는 계산 불가
#  shoulder_neck_gap, shoulder_fwd — MediaPipe 에선 Neck == 어깨중점이라 항등적으로 0 (정보 없음).
#    연구 코드는 0 을 그대로 내지만 앱은 계산하지 않는다 (mediapipe_computable=False, spec §3)
SKIP_PREFIX = ("spine_", "kneefoot_thigh", "neck_angle", "shoulder_neck_gap", "shoulder_fwd")


def main():
    lm = load_landmarks()
    sample = pd.read_parquet(OUT / "mp" / "sample.parquet")
    keys, arr, flipped = build_mp_arrays(lm, sample, "direct")
    print(f"(클립,뷰) {len(keys)}, y반전={flipped}")

    rng = np.random.default_rng(0)
    # Back/Waist 는 MediaPipe 에 없어 항상 NaN — 결측 검사에서 제외
    mp_idx = [j for j, name in enumerate(JOINTS_SHORT) if name not in ("Back", "Waist")]
    cases = []
    order = rng.permutation(len(keys))
    for i in order:
        P = arr[i]
        for t in range(P.shape[0]):
            if np.isnan(P[t][mp_idx]).any():
                continue
            cases.append((int(i), int(t)))
            break
        if len(cases) >= N_FRAMES:
            break
    print(f"선택 프레임 {len(cases)}")

    payload = []
    for i, t in cases:
        P = arr[i : i + 1, t : t + 1]  # (1,1,24,3)
        F = compute_frame_features(P)
        feats = {}
        for k, v in F.items():
            if k.startswith(SKIP_PREFIX):
                continue
            val = float(v[0, 0])
            if np.isfinite(val):
                feats[k] = round(val, 5)
        joints = {name: [round(float(x), 5) for x in P[0, 0, j]] for j, name in enumerate(JOINTS_SHORT)}
        # Back/Waist 는 MediaPipe 에 없다 (NaN) — Kotlin 은 아예 관절을 만들지 않으므로 제외
        joints = {k: v for k, v in joints.items() if not any(np.isnan(v))}
        payload.append(dict(clip=str(keys.clip_id.iloc[i]), view=str(keys.view_letter.iloc[i]), frame=t,
                            joints=joints, features=feats))

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text(json.dumps(dict(
        note="Generated by research/aihub_fitness/export_port_fixture.py — Kotlin PostureCore 파리티 검증용",
        joint_order=JOINTS_SHORT,
        mp_map={k: (list(v) if isinstance(v, tuple) else v) for k, v in MP_MAP.items() if v is not None},
        cases=payload,
    ), ensure_ascii=False, indent=1), encoding="utf-8")

    # 유닛 테스트용 단순 텍스트 (org.json 스텁 문제 회피)
    lines = ["# posture core parity fixture — 자동 생성, 수정 금지", "# CASE <clip> <view> <frame> / J <joint> x y z / F <feature> value / END"]
    for c in payload:
        lines.append(f"CASE {c['clip']} {c['view']} {c['frame']}")
        for name, xyz in c["joints"].items():
            lines.append(f"J {name} {xyz[0]} {xyz[1]} {xyz[2]}")
        for name, val in c["features"].items():
            lines.append(f"F {name} {val}")
        lines.append("END")
    DEST.with_suffix(".txt").write_text("\n".join(lines), encoding="utf-8")

    n_feats = len(payload[0]["features"]) if payload else 0
    print(f"[done] {DEST} (+ .txt)  케이스 {len(payload)}, 케이스당 피처 {n_feats}")


if __name__ == "__main__":
    main()
